// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTravelBlogs.Models;

namespace MyTravelBlogs.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyTravelBlogs.Models.Aboutme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("description");

                    b.Property<string>("photoUrl");

                    b.HasKey("Id");

                    b.ToTable("Aboutme");
                });

            modelBuilder.Entity("MyTravelBlogs.Models.Admin", b =>
                {
                    b.Property<int>("adminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<string>("password");

                    b.HasKey("adminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("MyTravelBlogs.Models.Blog", b =>
                {
                    b.Property<int>("blogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("blogContent");

                    b.Property<DateTime>("blogDate");

                    b.Property<string>("blogImage");

                    b.Property<string>("title");

                    b.HasKey("blogId");

                    b.ToTable("blogs");
                });

            modelBuilder.Entity("MyTravelBlogs.Models.Comment", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("blogId");

                    b.Property<string>("commentContent");

                    b.Property<string>("mail");

                    b.Property<int>("userName");

                    b.HasKey("commentId");

                    b.HasIndex("blogId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("MyTravelBlogs.Models.Comment", b =>
                {
                    b.HasOne("MyTravelBlogs.Models.Blog", "blog")
                        .WithMany("Comments")
                        .HasForeignKey("blogId");
                });
#pragma warning restore 612, 618
        }
    }
}
